name: 构建Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - name: 设置JDK环境
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: 设置Android SDK
        uses: android-actions/setup-android@v2
        
      - name: 安装SDL2_ttf依赖
        run: |
          mkdir -p app/src/main/jni/SDL2_ttf
          git clone https://github.com/libsdl-org/SDL_ttf.git app/src/main/jni/SDL2_ttf
          
      - name: 复制游戏源代码
        run: |
          mkdir -p app/src/main/assets
          cp -f simhei.ttf app/src/main/assets/
          cp -f game2048.h app/src/main/jni/
          cp -f game2048_core.c app/src/main/jni/
          cp -f game2048_gui_fixed.c app/src/main/jni/
          
      - name: 授予Gradle执行权限
        run: chmod +x ./gradlew
        
      - name: 使用Gradle构建APK
        run: ./gradlew assembleRelease
        
      - name: 签名APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: 上传APK
        uses: actions/upload-artifact@v3
        with:
          name: game2048-apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}} 