name: 构建Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v1
        with:
          submodules: 'recursive'
          
      - name: 设置JDK环境
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: 安装SDL2依赖
        run: |
          mkdir -p app/src/main/jni/SDL
          git clone https://github.com/libsdl-org/SDL.git app/src/main/jni/SDL
          
      - name: 安装SDL2_ttf依赖
        run: |
          mkdir -p app/src/main/jni/SDL2_ttf
          git clone https://github.com/libsdl-org/SDL_ttf.git app/src/main/jni/SDL2_ttf
          
      - name: 复制游戏源代码
        run: |
          mkdir -p app/src/main/assets
          cp -f simhei.ttf app/src/main/assets/ || true
          cp -f game2048.h app/src/main/jni/ || true
          cp -f game2048_core.c app/src/main/jni/ || true
          cp -f game2048_gui_fixed.c app/src/main/jni/ || true
          
      - name: 授予Gradle执行权限
        run: chmod +x ./gradlew || true
        
      - name: 使用Gradle构建APK
        run: ./gradlew assembleRelease || true
        
      - name: 签名APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: 创建发布目录
        run: mkdir -p release
        
      - name: 复制签名APK到发布目录
        run: cp ${{steps.sign_app.outputs.signedReleaseFile}} release/game2048.apk || true
      
      - name: 打包发布文件
        run: tar -czvf game2048-release.tar.gz release
      
      - name: 上传打包文件
        uses: actions/upload-artifact@v1
        with:
          name: game2048-release
          path: game2048-release.tar.gz 