name: 构建Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v1
          
      - name: 设置JDK环境
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: 安装SDL2依赖
        run: |
          mkdir -p app/src/main/jni/SDL
          git clone https://github.com/libsdl-org/SDL.git app/src/main/jni/SDL
          
      - name: 安装SDL2_ttf依赖
        run: |
          mkdir -p app/src/main/jni/SDL2_ttf
          git clone https://github.com/libsdl-org/SDL_ttf.git app/src/main/jni/SDL2_ttf
          
      - name: 复制游戏源代码
        run: |
          mkdir -p app/src/main/assets
          ls -la
          pwd
          cp -f *.ttf app/src/main/assets/ || true
          cp -f *.h app/src/main/jni/ || true
          cp -f *.c app/src/main/jni/ || true
          
      - name: 授予Gradle执行权限
        run: chmod +x ./gradlew || true
        
      - name: 使用Gradle构建APK
        run: ./gradlew assembleRelease || true
        
      - name: 签名APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      # 直接创建GitHub Release
      - name: 创建Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          
      # 上传APK作为Release资产
      - name: 上传Release资产
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{steps.sign_app.outputs.signedReleaseFile}}
          asset_name: game2048.apk
          asset_content_type: application/vnd.android.package-archive 